import { DocumentResponse } from "@features/document/document.types.ts";

export const useDocument = (documentId: string) => {
  // const { data: document, isLoading, isError } = useDocumentQuery(documentId);
  const document: DocumentResponse = {
    id: documentId,
    title: "Document Title",
    tiles: [
      {
        id: "tile-id-1",
        content: "Tile Content",
        xPosition: 0,
        yPosition: 0,
        width: 2,
        height: 2,
      },
      {
        id: "tile-id-2",
        content: "Tile Content",
        xPosition: 2,
        yPosition: 0,
        width: 3,
        height: 2,
      },
      {
        id: "tile-id-3",
        content: "Tile Content",
        xPosition: 5,
        yPosition: 0,
        width: 2,
        height: 2,
      },
      {
        id: "tile-id-4",
        content: "Tile Content",
        xPosition: 0,
        yPosition: 2,
        width: 2,
        height: 2,
      },
      {
        id: "tile-id-5",
        content: "Tile Content",
        xPosition: 2,
        yPosition: 2,
        width: 3,
        height: 2,
      },
      {
        id: "tile-id-6",
        content: "Tile Content",
        xPosition: 5,
        yPosition: 2,
        width: 2,
        height: 2,
      },
      {
        id: "tile-id-7",
        content: "Tile Content",
        xPosition: 0,
        yPosition: 4,
        width: 2,
        height: 3,
      },
      {
        id: "tile-id-8",
        content: "Tile Content",
        xPosition: 2,
        yPosition: 4,
        width: 3,
        height: 2,
      },
      {
        id: "tile-id-9",
        content: "Tile Content",
        xPosition: 5,
        yPosition: 4,
        width: 2,
        height: 3,
      },
      {
        id: "tile-id-10",
        content: "Tile Content",
        xPosition: 0,
        yPosition: 7,
        width: 3,
        height: 2,
      },
      {
        id: "tile-id-11",
        content: "Tile Content",
        xPosition: 3,
        yPosition: 7,
        width: 2,
        height: 2,
      },
      {
        id: "tile-id-12",
        content: "Tile Content",
        xPosition: 5,
        yPosition: 7,
        width: 3,
        height: 2,
      },
      {
        id: "tile-id-13",
        content: "Tile Content",
        xPosition: 0,
        yPosition: 9,
        width: 2,
        height: 2,
      },
      {
        id: "tile-id-14",
        content: "Tile Content",
        xPosition: 2,
        yPosition: 9,
        width: 2,
        height: 2,
      },
      {
        id: "tile-id-15",
        content: "Tile Content",
        xPosition: 4,
        yPosition: 9,
        width: 2,
        height: 2,
      },
      {
        id: "tile-id-16",
        content: "Tile Content",
        xPosition: 6,
        yPosition: 9,
        width: 3,
        height: 2,
      },
      {
        id: "tile-id-17",
        content: "Tile Content",
        xPosition: 0,
        yPosition: 11,
        width: 3,
        height: 3,
      },
      {
        id: "tile-id-18",
        content: "Tile Content",
        xPosition: 3,
        yPosition: 11,
        width: 3,
        height: 2,
      },
      {
        id: "tile-id-19",
        content: "Tile Content",
        xPosition: 6,
        yPosition: 11,
        width: 3,
        height: 2,
      },
      {
        id: "tile-id-20",
        content: "Tile Content",
        xPosition: 0,
        yPosition: 14,
        width: 4,
        height: 2,
      },
      {
        id: "tile-id-21",
        content: "Tile Content",
        xPosition: 4,
        yPosition: 14,
        width: 3,
        height: 2,
      },
      {
        id: "tile-id-22",
        content: "Tile Content",
        xPosition: 7,
        yPosition: 14,
        width: 3,
        height: 2,
      },
      {
        id: "tile-id-23",
        content: "Tile Content",
        xPosition: 0,
        yPosition: 16,
        width: 3,
        height: 3,
      },
      {
        id: "tile-id-24",
        content: "Tile Content",
        xPosition: 3,
        yPosition: 16,
        width: 3,
        height: 3,
      },
      {
        id: "tile-id-25",
        content: "Tile Content",
        xPosition: 6,
        yPosition: 16,
        width: 3,
        height: 3,
      },
    ],
  };

  const isLoading = false;
  const isError = false;

  return { document, isLoading, isError };
};
