name: "User Story"
description: "Create a new user story to describe a feature or requirement from an end-user perspective."
title: "As a [role] I want [objective] for [motivation]"
labels: [ "userstory" ]
projects: ["jathavaan/5"]
assignees:
  - jathavaan

body:
  - type: textarea
    id: user_story
    attributes:
      label: "User story description"
      description: "Describe the feature in detail explaining how the feature should work in a happy- and unhappy-path scenarios"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: "Priority"
      description: "How critical is this user story?"
      options:
        - High
        - Medium
        - Low
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: "Acceptance Criteria"
      description: "Define the conditions that must be met for this user story to be considered complete."
      placeholder: |
        - Given [some context], when [action happens], then [expected outcome].
        - The feature should function correctly under [specific condition].
    validations:
      required: true

  - type: textarea
    id: dependencies
    attributes:
      label: "Dependencies"
      description: "List any dependencies (e.g., other features, APIs, services) required for this user story to be completed."
      placeholder: "- Dependent on API endpoint X"
    validations:
      required: false

  - type: markdown
    attributes:
      value: "## Non-functional requirements"

  - type: markdown
    attributes:
      value: |
        - Must load within 500ms
        - Should work on mobile and desktop
        - Should comply with accessibility guidelines

  - type: markdown
    attributes:
      value: "## Resources"

  - type: markdown
    attributes:
      value: |
        - [API Docs](https://localhost:7189/swagger/index.html#/)
        - [Dribbble](https://dribbble.com/)
